name=KryptKernel
version=1.0.0
author=Diego
maintainer=Diego
sentence=Lightweight OS Kernel for ESP32
paragraph=A modular monolithic kernel built on top of FreeRTOS and LittleFS.
category=System
url=https://github.com/DlopedDtorred/KryptKernel
architectures=esp32
includes=Krypt.h
